---
title: "Social Media Multi regression"
author: "Yuefei Chen"
date: "2024-04-14"
output:
  pdf_document: default
  html_document: default
---

## The second part: Social media data


### Model development
Running the following code, we build a multiple regression model based on rent house data. Its independent variables "Instagram_value", "Linkedin_value", "Snapchat_value", "Twitter_value", "Whatsapp_Wechat_value", "Youtube_value", "OTT_Netflix_Hulu_Prime_video_value", "Reddit_value", "job_interview_calls", "networking_done_with_coffee_chats", "learning_done_in_terms_of_items_created". The dependent variable is "felt_the_entire_week". 

```{R}
library(readr)
APP_data <- read_csv("Dataset/Social Media_cleaned.csv")
APP_data <- APP_data[c(1:22), c(1:2, 4:5, 7:8, 10:11, 13:14, 16:17, 19:20, 22:23, 25:33)]
str(APP_data)
```
	
```{R}
fit <- lm(felt_the_entire_week ~ Instagram_value + Linkedin_value + Snapchat_value + Twitter_value + Whatsapp_Wechat_value + Youtube_value + OTT_Netflix_Hulu_Prime_video_value + Reddit_value + job_interview_calls + networking_done_with_coffee_chats + learning_done_in_terms_of_items_created, data=APP_data)
fit
```


### Model Acceptance
In the summary of the model, we focus on R squared value, coefficients, and P-value of each coefficient. The R-squared value is 0.4434 and Adjust R-squared value is -0.1688. It shows there is a low proportion of variance in the dependent variable can be explained by the independent variables. Therefore, we use stepAIC to find an optimal model.
```{R}
summary(fit)
coefficients(fit)
```
```{R}
library(MASS)
step <- stepAIC(fit, direction="both")
fit2 <- lm(felt_the_entire_week ~ Instagram_value + Whatsapp_Wechat_value + 
    job_interview_calls, data = APP_data)

```
### Residual Analysis
QQ plot is used in these residual analysis. We can conclude that most of residual points are located in a straight line. It satisfies normal distribution. 

```{R}
confint(fit2,level=0.95)
fitted(fit2)
residuals(fit2)
```


```{R}
library(car)
qqPlot(fit2, main="QQ Plot")
```


### Prediction
We set a data point with Instagram_value = 5, Whatsapp_Wechat_value = 5 and, job_interview_calls = 0, then the feeling score of the entire week we predict is approximate to 3
```{R}
predict.lm(fit2, data.frame(Instagram_value = 5, Whatsapp_Wechat_value = 5, job_interview_calls = 0))
```


### Model Accuracy
The accuracy is based on summary of the model and we also calculate the MSE and RMSE for the model. The MSE is 0.3846858 and RMSE is 0.6202304.
```{R}
summary(fit2)
predictions <- predict(fit2, APP_data)
mse <- mean((APP_data$felt_the_entire_week - predictions)^2)
rmse <- sqrt(mse)
cat("MSE: ", mse, "\n")
cat("RMSE: ", rmse, "\n")

```