---
title: "HW7 Multiple Regression Yuefei Chen"
author: "Yuefei Chen"
date: "2024-04-12"
output:
  html_document: default
  pdf_document: default
---

## The first part: Rent house Data

### Model development
Running the following code, we build a multiple regression model based on rent house data. Its independent variables "area", "rooms", "bathroom", "parking spaces", "hoa", "property tax", "fire insurance". The dependent variable is "rent amount".

```{R}
library(readr)
house_data <- read_csv("Dataset/Rent_House_random_200_multi_regression.csv")
house_data <- house_data[, c(1:4, 6:11)]
str(house_data)
```
```{R}
reg_data <- house_data[,-c(5,6)]
fit <- lm(rent_amount~area+rooms+bathroom+parking_spaces+hoa+property_tax+fire_insurance, data=reg_data)
fit
```

### Model Acceptance
In the summary of the model, we focus on R squared value, coefficients, and P-value of each coefficient. The R-squared value is 0.9835 and Adjust R-squared value is 0.9829. It shows there is a high proportion of variance in the dependent variable can be explained by the independent variables. The result of coefficient is shown in the following table. P-value result shows that the "area", "hoa", and "fire insurance" are variables which have a significant relationship with the "rent amount" variable. In addition, we use anova to compare full model and reduced model. The result shows that only keeping "area", "hoa", and "fire insurance" does not improve the model performance. Therefore, we use stepAIC to find an optimal model. It contains "area", "rooms", "bathroom", "hoa", "fire insurance".

```{R}
summary(fit)
coefficients(fit)
```
```{R}
library(MASS)
fit1 <- fit
fit2 <- lm(rent_amount ~ area + hoa + fire_insurance, data = reg_data)
# compare models
anova(fit1, fit2)
step <- stepAIC(fit, direction="both")
fit3 <- lm(rent_amount ~ area + rooms + bathroom + hoa + fire_insurance, data = reg_data)
```
### Residual Analysis
Two plots are used in these residual analysis. The first plot is QQ plot. We can conclude that most of residual points are located in a straight line. It satisfies normal distribution. Simlarily, the componet + residual plots tells that each variable satisfies the normal distribution. The regression can be regarded as normal distribution.
```{R}
confint(fit3,level=0.95)
fitted(fit3)
residuals(fit3)
```
```{R}
library(car)
qqPlot(fit3, main="QQ Plot")
```
```{R results='hide', warning=FALSE}
crPlots(fit3)
```
### Prediction
We set a data point with area = 120, rooms = 3, bathroom = 2, hoa = 0, fire insurance = 50, then the rent amount we predict is 3391.853.
```{R}
predict.lm(fit3, data.frame(area = 120, rooms = 3, bathroom = 2, hoa = 0, fire_insurance = 50))
```


### Model Accuracy
The accuracy is based on summary of the model and we also calculate the MSE and RMSE for the model. The R-squared value is 0.9834, and the Adjusted R-squared value is 0.983. The MSE is 198405.6 and RMSE is 445.4274.

```{R}
summary(fit3)
predictions <- predict(fit3, reg_data)
mse <- mean((reg_data$rent_amount - predictions)^2)
rmse <- sqrt(mse)
cat("MSE: ", mse, "\n")
cat("RMSE: ", rmse, "\n")
```

