---
title: "HW8_Social_Media_Logistics_Regression_Yuefei_Chen"
author: "Yuefei Chen"
date: "2024-04-20"
output:
  pdf_document: default
  html_document: default
---

### Model development
Running the following code, we build a multiple regression model based on rent house data. Its independent variables "Instagram_value", "Linkedin_value", "Snapchat_value", "Twitter_value", "Whatsapp_Wechat_value", "Youtube_value", "OTT_Netflix_Hulu_Prime_video_value", "Reddit_value", "job_interview_calls", "networking_done_with_coffee_chats", "learning_done_in_terms_of_items_created". The dependent variable is "Tired_waking_up_in_morning".

```{R}
library(readr)
library(ggplot2)
library(pROC)
APP_data <- read_csv("Dataset/Social Media_cleaned.csv")
APP_data <- APP_data[c(1:22), c(1:2, 4:5, 7:8, 10:11, 13:14, 16:17, 19:20, 22:23, 25:33)]
str(APP_data)
```

```{R}
APP_data$Tired_waking_up_in_morning <- as.factor(APP_data$Tired_waking_up_in_morning)
#reg_data$area <- as.factor(reg_data$area)
#reg_data$rooms <- as.factor(reg_data$rooms)
#reg_data$bathroom <- as.factor(reg_data$rooms)
#reg_data$rent_amount <- as.factor(reg_data$rent_amount)
logistic <- glm(Tired_waking_up_in_morning~Instagram_value + Linkedin_value + Snapchat_value + Twitter_value + Whatsapp_Wechat_value + Youtube_value + OTT_Netflix_Hulu_Prime_video_value + Reddit_value + job_interview_calls + networking_done_with_coffee_chats + learning_done_in_terms_of_items_created, data=APP_data, family="binomial")

```

### Model Acceptance and Residual Analysis
In the summary of the model, we focus on R squared value, coefficients, and P-value of each coefficient. The R-squared value is 1 and p value is 0.003830217. The Pseudo R-square shows there is an improvement and better than baseline model. The p-value based on Likelihood Ratio Test shows that the model improvement is significant. The AIC value is 25. 

```{R}
summary(logistic)
```

```{R}
ll.null <- logistic$null.deviance/-2
ll.proposed <- logistic$deviance/-2
(ll.null - ll.proposed) / ll.null
1 - pchisq(2*(ll.proposed - ll.null), df=(length(logistic$coefficients)-1))
```











### Prediction
The data will be predicted in the model and the predicted probability of the rent house will be furnitured table is as follows.
```{R}
predicted.data <- data.frame(probability.of.Tired_waking_up_in_morning=logistic$fitted.values,Tired_waking_up_in_morning=APP_data$Tired_waking_up_in_morning)
predicted.data <- predicted.data[order(predicted.data$probability.of.Tired_waking_up_in_morning, decreasing=FALSE),]
predicted.data$rank <- 1:nrow(predicted.data)
ggplot(data=predicted.data, aes(x=rank, y=probability.of.Tired_waking_up_in_morning)) +
geom_point(aes(color=Tired_waking_up_in_morning), alpha=1, shape=4, stroke=2) +
xlab("Index") +
ylab("Predicted probability of the rent house will be furnitured")
```

### Model Accuracy
Receiver operating characteristic (ROC) curves is shown as follows. The area under the curve (AUC) is 1, which means the accuracy of the model is considered outstanding.

```{R}
roc(APP_data$Tired_waking_up_in_morning,logistic$fitted.values,plot=TRUE, legacy.axes=TRUE, col="#377eb8")

```
